resource "google_artifact_registry_repository" "xport_images" {
  provider      = google
  location      = var.region
  repository_id = var.repository_name
  description   = "Artifact Registry repository to uploafd xport images generated by the pipeline"
  format        = "DOCKER"
}

