; Command to extract the enough information of the VM
; gcloud compute ssh <VM_NAME> \
;   --zone=us-central1-a \
;   --project=test-PROJECT_ID \
;   --dry-run
 
[xport]
xport-vm-micro ansible_host=<VM_HOST> ansible_user=<USER> ansible_ssh_private_key_file=<SSH_KEY_PATH>

