; Command to extract the enough information of the VM
; gcloud compute ssh xport-vm-micro \
;   --zone=us-central1-a \
;   --project=test-project-504013 \
;   --dry-run
 
[xport]
xport-vm-micro ansible_host=34.170.13.113 ansible_user=bryan ansible_ssh_private_key_file=/home/bryan/.ssh/google_compute_engine

