# https://docs.ansible.com/projects/ansible/latest/playbook_guide/playbooks_intro.html#playbook-syntax
---
- name: Configure VM
  hosts: xport
  become: true

  tasks:
    - name: Update apt package
      ansible.builtin.apt:
        update_cache: true
        upgrade: yes

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add Ansible user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Pull Docker image from Docker Hub
      community.docker.docker_image:
        name: mrasaltanas/xport-app
        tag: "{{ image_tag }}"
        source: pull

    - name: Initialize Docker container
      community.docker.docker_container:
        name: xport-app-container
        image: "mrasaltanas/xport-app:{{ image_tag }}"
        state: started
        restart_policy: always
        published_ports:
          - "5500:5500"   

    - name: Wait for Application Port
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 5500
        delay: 2
        timeout: 60

    - name: Test X-Port application
      ansible.builtin.uri:
        url: http://127.0.0.1:5500
        method: GET
        status_code: 200
      register: xport_healthcheck
      retries: 10
      delay: 3
      until: xport_healthcheck.status == 200

    - name: Show application status
      ansible.builtin.debug:
        msg: "X-Port application is running successfully. HTTP status: {{ xport_healthcheck.status }}"