# https://docs.ansible.com/projects/ansible/latest/playbook_guide/playbooks_intro.html#playbook-syntax
---
- name: Configure VM
  hosts: xport
  remote_user: bryan
  become: true

  tasks:
    - name: Update vm package
      ansible.builtin.apt:
        update_cache: true
        upgrade: yes

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add Ansible user to Docker group
      ansible.builtin.user:
        name: bryan
        groups: docker
        append: true

    - name: Pull Docker image from Docker Hub
      community.docker.docker_image:
        name: mrasaltanas/xport-app
        tag: latest
        source: pull

    - name: Initialize Docker container
      community.docker.docker_container:
        name: xport-app-container
        image: mrasaltanas/xport-app:latest
        state: started
        restart_policy: always
        published_ports:
          - "5500:5500"   