name: xport ci pipeline

"on":
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest -v tests/

  docker-build:
    needs: validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t xport-app .

      - name: Run Docker container
        run: |
          docker run -d -p 5500:5500 xport-app

      - name: Test Docker container
        run: |
          sleep 5 # Wait for the container to start
          curl http://localhost:5500
